### ISSUE TITLE
Tracking issue: Nota editor

### ISSUE THREAD

**Issue by willcrichton** [nota-lang/nota#11]
Navigation:
- [ ] Minimap of section headers (a la Overleaf)

Viewing:
- [ ] Verbatim text should be monospace
- [ ] Need to trim trailing whitespace or otherwise highlight whitespace on empty lines
- [ ] Leading whitespace in text blocks should be shown as monospace font and not serif, since otherwise it's hard to see the level of indentation

Editing:
- [ ] Indentation of Javascript within Nota pct-commands is not correct
- [ ] Labels should be autosuggested for `@Ref`
- [ ] When writing `|{` should autocomplete `}|` and not `}`
- [ ] Add ability to delete an entire command
- [ ] Add snippets for common things like `@a[href="..."]{...}`

Errors:
- [ ] Runtime errors don't use source maps
- [ ] Syntax errors should be shown in editor, not as standalone text

Pipeline:
- [ ] editor needs to cleanup temp directory containing build files on exit (see commented out code in `server.ts`)
