### ISSUE TITLE
Tracking issue: Nota components

### ISSUE THREAD

**Issue by willcrichton** [nota-lang/nota#12]
- [ ] Footnotes aren't working?
- [ ] Inference rules are too verbose
- [ ] Need some kind of namespacing or component hierarchy / organization. 
- [ ] Need to establish conventions on JSX.Element vs. React.ReactNode vs. React.FC vs. etc for when elements take React stuff as input.
- [ ] Inspecting references within a reference's tooltip causes layout issues
