### ISSUE TITLE
Tracking issue: Bikeshed emporium

### ISSUE THREAD

**Issue by willcrichton** [nota-lang/nota#13]
- [ ] should probably adopt camelCase since that's the Javascripty thing to do
- [ ] Listing -> Code? pretty outdated terminology
- [ ] `@Definition` and `@Ref`, should maybe `@Definition` -> `@Def`?
